{% set name = "aiida-wannier90" %}
{% set version = "2.2.0" %}
{% set build = 0 %}
{% set name_code = name + ".code" %}

package:
  name: {{ name|lower }}.meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f75ce0c37f2a0c4d286cb5ff9c71c34784dece233b40f80f900e69d1e781ba28

build:
  number: {{ build }}
  noarch: python

requirements:
  run:
    - {{ pin_subpackage(name, exact=True) }}
    - {{ pin_subpackage(name_code, exact=True) }}


outputs:

  - name: {{ name }}
    build:
      noarch: python
      script: 'python -m pip install . --no-deps --ignore-installed -vvv '
    requirements:
      host:
        - pip
        - python >=3.6
        - reentry
      run:
        - aiida-core >=2.0,<3
        - python >=3.8
      run_constrained:
        - {{ name_code }} =={{ version }}
    test:
      imports:
        - aiida_wannier90
      commands:
        - pip check
      requires:
        - pip

  - name: {{ name_code }}
    build:
      noarch: python
    requirements:
      run:
        - wannier90 >=1,<4
    test:
      commands:
        - which wannier90.x

about:
  home: https://github.com/aiidateam/aiida-wannier90
  summary: AiiDA Plugin for the Wannier90 code
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
